import { useState, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import BottomNav from "@/components/BottomNav";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { useLanguage } from "@/contexts/LanguageContext";
import { toast } from "sonner";
import { ArrowLeft, FileDown, FileText, Sparkles, Loader2, Download } from "lucide-react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

type CardTier = "bronze" | "silver" | "gold" | "legendary";

const tierConfig: Record<CardTier, { label: string; bg: string; border: string; text: string; glow: string }> = {
  bronze: { label: "Bronze", bg: "bg-gradient-to-br from-amber-900/80 to-amber-950", border: "border-amber-700/50", text: "text-amber-400", glow: "" },
  silver: { label: "Prata", bg: "bg-gradient-to-br from-slate-400/30 to-slate-600/30", border: "border-slate-400/50", text: "text-slate-300", glow: "" },
  gold: { label: "Ouro", bg: "bg-gradient-to-br from-yellow-600/40 to-yellow-900/40", border: "border-yellow-500/60", text: "text-yellow-400", glow: "shadow-[0_0_30px_hsl(45,100%,50%,0.2)]" },
  legendary: { label: "Lendária", bg: "bg-gradient-to-br from-yellow-400/20 via-black to-yellow-600/20", border: "border-yellow-400/80", text: "text-yellow-300", glow: "shadow-[0_0_40px_hsl(45,100%,55%,0.4)]" },
};

const ExportCenter = () => {
  const navigate = useNavigate();
  const { profile } = useAuth();
  const { lang } = useLanguage();
  const [exporting, setExporting] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const getProfileCompleteness = (): number => {
    if (!profile) return 0;
    const fields = ["full_name", "bio", "sport", "position", "height_cm", "weight_kg", "birth_date", "address", "avatar_url", "dominant_foot", "wingspan_cm"];
    const filled = fields.filter(f => (profile as any)[f]);
    return Math.round((filled.length / fields.length) * 100);
  };

  const getTier = (): CardTier => {
    const pct = getProfileCompleteness();
    if (pct >= 90) return "legendary";
    if (pct >= 70) return "gold";
    if (pct >= 50) return "silver";
    return "bronze";
  };

  const tier = getTier();
  const completeness = getProfileCompleteness();
  const config = tierConfig[tier];

  const exportPDF = async () => {
    if (!profile) return;
    setExporting(true);
    try {
      const doc = new jsPDF("p", "mm", "a4");
      const w = doc.internal.pageSize.getWidth();

      // Header
      doc.setFillColor(10, 10, 10);
      doc.rect(0, 0, w, 45, "F");
      doc.setTextColor(100, 255, 100);
      doc.setFontSize(22);
      doc.text("TALENTO RADAR", 15, 20);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text(lang === "en" ? "Professional Report" : "Relatório Profissional", 15, 30);
      doc.text(new Date().toLocaleDateString(lang === "en" ? "en-US" : "pt-BR"), 15, 37);

      // Name & Info
      doc.setTextColor(30, 30, 30);
      doc.setFontSize(18);
      doc.text(profile.full_name || "—", 15, 58);
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`${profile.sport || "—"} | ${profile.position || "—"}`, 15, 66);
      doc.text(`${profile.address || "—"}`, 15, 72);

      // Physical metrics
      let y = 88;
      doc.setFontSize(13);
      doc.setTextColor(30, 30, 30);
      doc.text(lang === "en" ? "Physical Metrics" : "Métricas Físicas", 15, y);
      y += 8;
      doc.setFontSize(10);

      const metrics = [
        [lang === "en" ? "Height" : "Altura", profile.height_cm ? `${profile.height_cm} cm` : "—"],
        [lang === "en" ? "Weight" : "Peso", profile.weight_kg ? `${profile.weight_kg} kg` : "—"],
        [lang === "en" ? "Wingspan" : "Envergadura", profile.wingspan_cm ? `${profile.wingspan_cm} cm` : "—"],
        [lang === "en" ? "Dominant Foot" : "Pé Dominante", profile.dominant_foot || "—"],
        [lang === "en" ? "Birth Date" : "Data de Nascimento", profile.birth_date || "—"],
      ];

      metrics.forEach(([label, value]) => {
        doc.setTextColor(100, 100, 100);
        doc.text(label, 15, y);
        doc.setTextColor(30, 30, 30);
        doc.text(value, 80, y);
        y += 7;
      });

      // Bio
      if (profile.bio) {
        y += 5;
        doc.setFontSize(13);
        doc.text("Bio", 15, y);
        y += 7;
        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);
        const lines = doc.splitTextToSize(profile.bio, w - 30);
        doc.text(lines, 15, y);
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by Talento Radar", 15, 285);

      doc.save(`${profile.full_name || "atleta"}_relatorio.pdf`);
      toast.success(lang === "en" ? "PDF exported!" : "PDF exportado!");
    } catch (e) {
      toast.error("Erro ao exportar");
    }
    setExporting(false);
  };

  const exportCard = async () => {
    if (!cardRef.current) return;
    setExporting(true);
    try {
      const canvas = await html2canvas(cardRef.current, {
        backgroundColor: "#000",
        scale: 2,
      });
      const link = document.createElement("a");
      link.download = `${profile?.full_name || "atleta"}_card.png`;
      link.href = canvas.toDataURL();
      link.click();
      toast.success(lang === "en" ? "Card exported!" : "Carta exportada!");
    } catch {
      toast.error("Erro ao exportar");
    }
    setExporting(false);
  };

  const age = profile?.birth_date
    ? Math.floor((Date.now() - new Date(profile.birth_date).getTime()) / (365.25 * 24 * 60 * 60 * 1000))
    : null;

  return (
    <div className="min-h-screen bg-background pb-20">
      <header className="sticky top-0 z-50 glass border-b border-border/50 px-4 py-3">
        <div className="max-w-2xl mx-auto flex items-center gap-3">
          <button onClick={() => navigate(-1)} className="text-muted-foreground hover:text-foreground">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <FileDown className="w-5 h-5 text-primary" />
          <span className="font-display font-bold text-lg text-foreground">
            {lang === "en" ? "Export Center" : "Central de Exportação"}
          </span>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-4 py-4 space-y-6">
        {/* PDF Export */}
        <div className="glass-card rounded-xl p-5 border border-border space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
              <FileText className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h3 className="font-display font-bold text-foreground">{lang === "en" ? "Professional Report" : "Relatório Profissional"}</h3>
              <p className="text-xs text-muted-foreground">{lang === "en" ? "Complete PDF with metrics and resume" : "PDF completo com métricas e currículo"}</p>
            </div>
          </div>
          <Button onClick={exportPDF} disabled={exporting} className="w-full">
            {exporting ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Download className="w-4 h-4 mr-2" />}
            {lang === "en" ? "Export PDF" : "Exportar PDF"}
          </Button>
        </div>

        {/* FIFA Card */}
        <div className="glass-card rounded-xl p-5 border border-border space-y-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-yellow-500/10 flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-yellow-400" />
            </div>
            <div>
              <h3 className="font-display font-bold text-foreground">{lang === "en" ? "Digital Card" : "Carta Digital"}</h3>
              <p className="text-xs text-muted-foreground">Ultimate Team Style • {config.label}</p>
            </div>
          </div>

          <div className="flex justify-center">
            <Badge className={`${config.text} border-0 bg-black/50 text-xs`}>
              {completeness}% {lang === "en" ? "complete" : "completo"} → {config.label}
            </Badge>
          </div>

          {/* Card Preview */}
          <div className="flex justify-center">
            <div
              ref={cardRef}
              className={`w-64 rounded-2xl p-5 border-2 ${config.bg} ${config.border} ${config.glow} relative overflow-hidden`}
              style={{ aspectRatio: "2/3" }}
            >
              {/* Decorative lines */}
              <div className="absolute inset-0 opacity-10">
                <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-yellow-400 to-transparent" />
                <div className="absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-yellow-400 to-transparent" />
              </div>

              <div className="relative z-10 h-full flex flex-col items-center justify-between">
                {/* Top: Rating */}
                <div className="text-center">
                  <span className={`font-display text-4xl font-bold ${config.text}`}>
                    {completeness}
                  </span>
                  <p className="text-[10px] text-yellow-200/60 font-display uppercase tracking-wider">{config.label}</p>
                </div>

                {/* Avatar */}
                <div className="w-20 h-20 rounded-full bg-black/40 border-2 border-yellow-500/30 flex items-center justify-center">
                  {profile?.avatar_url ? (
                    <img src={profile.avatar_url} className="w-full h-full rounded-full object-cover" />
                  ) : (
                    <span className={`font-display text-2xl font-bold ${config.text}`}>{profile?.full_name?.charAt(0)}</span>
                  )}
                </div>

                {/* Name & Position */}
                <div className="text-center">
                  <p className="font-display font-bold text-white text-sm truncate max-w-full">{profile?.full_name}</p>
                  <p className="text-[10px] text-yellow-200/60">{profile?.position || "—"}</p>
                </div>

                {/* Stats */}
                <div className="grid grid-cols-3 gap-x-4 gap-y-1 text-center w-full">
                  <div><p className="text-yellow-200/40 text-[8px]">ALT</p><p className="text-white text-xs font-bold">{profile?.height_cm || "—"}</p></div>
                  <div><p className="text-yellow-200/40 text-[8px]">PES</p><p className="text-white text-xs font-bold">{profile?.weight_kg || "—"}</p></div>
                  <div><p className="text-yellow-200/40 text-[8px]">IDA</p><p className="text-white text-xs font-bold">{age || "—"}</p></div>
                </div>

                {/* Sport badge */}
                <Badge className="bg-yellow-500/20 text-yellow-300 border-yellow-500/30 text-[10px]">
                  {profile?.sport || "—"}
                </Badge>
              </div>
            </div>
          </div>

          <Button onClick={exportCard} disabled={exporting} variant="outline" className="w-full border-yellow-500/30 text-yellow-400 hover:bg-yellow-500/10">
            {exporting ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Download className="w-4 h-4 mr-2" />}
            {lang === "en" ? "Export Card" : "Exportar Carta"}
          </Button>
        </div>
      </main>

      <BottomNav />
    </div>
  );
};

export default ExportCenter;
